### PR TITLE
Added 'docs' folder to contain documentation

### LINKED ISSUE #179: Create documentation for UUF
Documentation should contain following.

- [x] Basic concepts (No JS/HB/Java)
- [ ] How to write an app (with an example scenario)
- [ ] Best practices - How to do stuff in the correct way
- [ ] Ref Guide
  - [x] JS global functions
  - [ ] Helpers
  - [ ] UUF Configurations (app.yml, component.yml, theme.yml)
  - [ ] UUF Maven plugin (archetypes, goals)

### PR DESCRIPTION
**Pull request by roonyh**
Resolves #179

### CODE REVIEW

**Comment by chamilad** [comment]
@roonyh If there is an issue for this, better to mention it with one of the keywords [1] to auto-close it once this is merged. 

[1] - https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by roonyh** [comment]
@chamilad Got it. Thanks! Looks like there is no issue for this yet.

**Comment by this** [comment]
@roonyh Please create an issue for this.

**Comment by this** [comment]
Closing as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).

**Pull request closed without merging**
